name: deployment

permissions:
  packages: write
  contents: read

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  releaseJob:
    name: Update version & deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ref: https://stackoverflow.com/questions/58177786/get-the-current-pushed-tag-in-github-actions
      - name: Set version env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo "TAG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # ref: https://stackoverflow.com/questions/65606498/how-to-access-github-tag-message-in-github-actions
      - name: Get and set tag message
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          git tag -l --format='%(contents:subject)' ${GITHUB_REF#refs/*/}
          echo "TAG_MESSAGE=$(git tag -l --format='%(contents:subject)' ${GITHUB_REF#refs/*/} | sed 's/[^ .,:[:alpha:][:digit:]]//g')" >> $GITHUB_ENV

      - name: Test env
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
          echo $TAG_VERSION
          echo ${{ env.TAG_VERSION }}
          echo ${{ env.TAG_MESSAGE }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      # ref: https://github.community/t/auto-update-package-json-on-publishing/16894
      - name: Update package version
        run: |
          npm --no-git-tag-version version ${{ env.RELEASE_VERSION }}

      # ref: https://github.com/marketplace/actions/npm-publish
      - name: NPM package publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          access: public
          registry: https://npm.pkg.github.com

      # Can not publish to github package registry since Github org has not been migrated to verified.inc yet.
      # - name: Github package publish
      #   uses: JS-DevTools/npm-publish@v3
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     access: public
      #     registry: https://npm.pkg.github.com

      # ref: https://github.com/marketplace/actions/delete-tag-and-release
      # - name: Delete the v tag
      #   uses: dev-drprasad/delete-tag-and-release@v1.1
      #   with:
      #     delete_release: true # default: false
      #     tag_name: ${{ env.TAG_VERSION }} # tag name to delete
      #     # repo: <owner>/<repoName> # target repo (optional). defaults to repo running this action
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete the v tag
        run: gh release delete ${{ env.TAG_VERSION }} --cleanup-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ref: https://github.com/marketplace/actions/add-commit
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Verified Inc
          author_email: liam@verified.inc
          message: '[Release ${{ env.RELEASE_VERSION }}] ${{ env.TAG_MESSAGE }}'
          add: '.'
          branch: main

      # ref: https://github.com/marketplace/actions/gh-release
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          tag_name: ${{ env.RELEASE_VERSION }}
          name: ${{ env.RELEASE_VERSION }}
          generate_release_notes: true
          draft: false
          prerelease: false
          target_commitish: main
